name       : adms
version    : 2.3.7
release    : 4
source     :
    - https://github.com/Qucs/ADMS/archive/refs/tags/release-2.3.7.tar.gz : 0d24f645d7ce0daa447af1b0cff1123047f3b73cc41cf403650f469721f95173
homepage   : https://github.com/Qucs/ADMS
license    : GPL-3.0-or-later
component  : office.scientific
summary    : ADMS is a code generator for the Verilog-AMS language
description: |
    ADMS is a code generator that converts electrical compact device models specified in high-level description language into ready-to-compile C code for the API of spice simulators. Based on transformations specified in XML language, ADMS transforms Verilog-AMS code into other target languages.
patterns   :
    - /usr/include
builddeps  :
    - perl-xml-libxml
setup      : |
    %cmake_ninja -DUSE_MAINTAINER_MODE=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
