name       : adms
version    : 2.3.7
release    : 3
source     :
    - https://github.com/Qucs/ADMS/archive/refs/tags/release-2.3.7.tar.gz : 0d24f645d7ce0daa447af1b0cff1123047f3b73cc41cf403650f469721f95173
license    : GPL-3.0-or-later
component  : office.scientific
summary    : ADMS is a code generator for the Verilog-AMS language
description: |
    ADMS is a code generator for the Verilog-AMS language
patterns   :
    - /usr/include
builddeps  :
    - perl-xml-libxml
setup      : |
    %cmake_ninja -DUSE_MAINTAINER_MODE=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
