name       : adms
version    : 2.3.6
release    : 1
source     :
    - https://github.com/Qucs/ADMS/archive/release-2.3.6.tar.gz : aaf3f635aae41e1c11913e09b8e1bc5eea64256dcec70f3f60d1b9a794af6053
license    : GPL-3.0-or-later
component  : office.scientific
summary    : ADMS is a code generator for the Verilog-AMS language
description: |
    ADMS is a code generator for the Verilog-AMS language
builddeps  :
    - perl-xml-libxml
setup      : |
    %cmake_ninja -DUSE_MAINTAINER_MODE=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - /usr/include